I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 555, in script
    edward "Hello %(player_name)s"
Exception: Sayer 'edward' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 555, in script
    edward "Hello %(player_name)s"
  File "C:\Users\lisan\Downloads\renpy-8.0.1-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\lisan\Downloads\renpy-8.0.1-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'edward' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.1.22070801
The Henhouse 1.0
Tue Dec  6 22:27:10 2022
